Ecommerece/ecommerce/ecommerce/urls.py

from django import urls
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from produto.api.viewsets import ProdutoViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'produtos', ProdutoViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("produto.urls", namespace="produto")),
    path("accounts/", include("allauth.urls")),
    path("api/", include(router.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Ecommerece/ecommerce/produto/urls.py
from django.db import router
from django.urls import path
from .views import HomePageView, AddCategoriaView, AddProdutoView, DeleteProdutoView, UpdateProdutoView, DetailProdutoView, ConfirmProdutoView, CarrinhoView, ConfirmCarrinhoView


app_name = "produto"

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("add_categoria/", AddCategoriaView.as_view(), name="categoria"),
    path("add_produto/", AddProdutoView.as_view(), name="produto"),
    path("exclui/<pk>", DeleteProdutoView.as_view(), name="delete"),
    path("atualiza/<pk>", UpdateProdutoView.as_view(), name="atualiza"),
    path("produto/<pk>", DetailProdutoView.as_view(), name="detalhe"),
    path("confirma/<pk>", ConfirmProdutoView.as_view(), name="confirma"),
    path("carrinho/", CarrinhoView.as_view(), name="carrinho"),
    path("carrinho/compras", ConfirmCarrinhoView.as_view(), name="confirm")
]

Ecommerece/ecommerce/templates/atualiza.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}

{% block title %}Atualizar {{ produto.nome }}{% endblock %}


{% block content %}
    <h2>Atualizar {{ produto.nome }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <div class="card-footer" style="text-align: right;">
            <button class="btn btn-success" type="submit">Atualizar</button>
            <a href="{% url 'produto:home' %}"><button type="button" class="btn btn-primary">Voltar</button></a>
          </div>
    </form>
{% endblock %}

Ecommerece/ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand navbar-dark bg-dark mb-3">
            <div class="container">
                <a class="navbar-brand" href="{% url 'produto:home' %}">E-JRGEEK</a>
                <a href="https://ejrgeekio.com/" target="_blank"><img src="https://ejrgeekio.files.wordpress.com/2021/07/cropped-cropped-icon-menor.png" class="img-fluid" style="max-width: 150px"></a>
                <ul class="navbar-nav">
                
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_logout' %}">Sair</a>
                        </li>
                
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_login' %}">Entrar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'account_signup' %}">Cadastro</a>
                        </li>
                
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% if user.is_authenticated %}
            <nav class="navbar navbar-expand navbar-dark bg-dark mb-3" style="margin-top: -33px;">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'produto:categoria' %}">Adicionar Categoria</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'produto:produto' %}">Adicionar produto</a>
                </li>
            </nav>
        {% endif %}
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

Ecommerece/ecommerce/templates/carrinho.html
{% extends 'base.html' %}

{% block content %}
  {% if produtos %}

    <div class="card-group">

    
    {% for produto in produtos %}
          <div class="card" style="margin-right: 5px;">

            <img class="card-img-top img-fluid" src="{{ produto.imagem.url }}" style="max-height: 200px;">
            
            <div class="card-body">
              
              <h5 class="card-title">{{ produto.nome }} </h5>
              
              <p class="card-text">{{ produto.preco }} R$</p>
            </div>
          </div>              
        {% endfor %}

      </div>
      <div style="margin-top: 10px;">
        <a href="{% url 'produto:home'%}"><button type="button" class="btn btn-outline-secondary"> Redefinir</button></a>
        <a href="{% url 'produto:confirm'%}"><button type="button" class="btn btn-outline-secondary"> Comprar </button></a>
      </div>
  {% else %}
      Não há produtos no carrinho
  {% endif %}
  

Ecommerece/ecommerce/templates/compra.html
{% extends 'base.html' %}

{% block title %} Compra {% endblock %}

{% block content %}
    <div class="container" style="margin: 0 auto;">
        <div class="row">
            <div class="col-md-5">
                <div class="project-info-box mt-0">
                    <h5>{{ produto.nome }}</h5>
                    <p class="mb-0">{{ produto.descricao }}</p>
                    <br>
                </div><!-- / project-info-box -->

                <div class="project-info-box">
                    <p><strong style="text-decoration: line-through;">{{ produto.preco }} R$</strong></p>
                    <p><strong style="font-weight: 900; font-size: 20px;">{{ preco_liquido }} R$</strong></p>
                </div><!-- / project-info-box -->

            </div><!-- / column -->

            <div class="col-md-7">
                <img src="{{ produto.imagem.url }}" alt="project-image" class="rounded" style=" width: 400px; height: 300px;">
                <div class="project-info-box">
                    <p><b>Categoria:</b> {{ produto.categoria }}</p>
                </div>
            </div>
    </div>
    {% if tipo %}
    
        <a href="{% url 'produto:confirma' pk=produto.id %}"><button type="button" class="btn btn-outline-primary">Finalizar</button></a>

    {% else %}
        Você não pode comprar esse produto, esteja logado como comprador ou cadastre-se como tal
        <br/>
        <br/>
        <a href="{% url 'produto:home' %}"><button type="button" class="btn btn-outline-primary">Voltar</button></a>
    {% endif %}

{% endblock %}

Ecommerece/ecommerce/templates/confirma.html
{% extends 'base.html' %}

{% block title %}Compra Finalizada{% endblock %}


{% block content %}
    {% if invalido %}
        Não podes comprar isso!
        <br/>
        <br/>
        <a href="{% url 'produto:home' %}"><button type="button" class="btn btn-outline-primary">Home</button></a>
    {% else %}
        Compra Finalizada com Sucesso, Volte sempre!
    {% endif %}
{% endblock %}

Ecommerece/ecommerce/templates/confirma_carrinho.html
{% extends 'base.html' %}

{% block title %}Compra Finalizada{% endblock %}


{% block content %}
    {% if invalido %}
        Não podes comprar isso!
        <br/>
        <br/>
        <a href="{% url 'produto:home' %}"><button type="button" class="btn btn-outline-primary">Home</button></a>
    {% else %}
        Compras Finalizadas com Sucesso, Volte sempre!
    {% endif %}
{% endblock %}

Ecommerece/ecommerce/templates/cria_categoria.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Criar Categoria{% endblock %}


{% block content %}
    <h2>Criar</h2>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button class="btn btn-success" type="submit">Criar</button>
    </form>
{% endblock %}

Ecommerece/ecommerce/templates/cria_produto.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Criar Produto{% endblock %}


{% block content %}
    <h2>Criar</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button class="btn btn-success" type="submit">Criar</button>
    </form>
{% endblock %}

Ecommerece/ecommerce/templates/delete.html
{% extends 'base.html' %}

{% block title %}Criar Produto{% endblock %}


{% block content %}
    <h2>Deseja deletar {{ produto.nome }}?</h2>
    <form method="post" style="text-align: right;">
        {% csrf_token %}   
        <a href="{% url 'produto:home' %}"><button type="button" class="btn btn-outline-primary">Voltar</button></a>
        <button class="btn btn-outline-danger" type="submit">Deletar</button>
    </form>
{% endblock %}

Ecommerece/ecommerce/templates/home.html
{% extends 'base.html' %}

{% block title %}E-JRGEEK{% endblock %}


{% block content %}

    {% if produtos %}

    <div class="card-group">

      
      {% for produto in produtos %}
          {% if produto.estoque > 0 %}
            <div class="card" style="margin-right: 5px;">

              <img class="card-img-top img-fluid" src="{{ produto.imagem.url }}" style="max-height: 200px;">
              
              <div class="card-body">
                
                <h5 class="card-title">{{ produto.nome }} </h5>
                
                <p class="card-text">{{ produto.preco }} R$</p>
                {% if produto.desconto %}
                  <p class="card-text">{{ produto.desconto }}% de desconto</p>
                {% endif %}
              
              </div>
              
              <div class="card-footer" style="text-align: right;">
                <a id="{{ produto.id }}"><button onclick="AddCarrinho('{{ produto.id}}')" type="button" class="btn btn-outline-secondary">Adicionar a carrinho</button></a>
                <a href="{% url 'produto:atualiza' pk=produto.id %}"><button type="button" class="btn btn-outline-primary">Atualizar</button></a>
                <a href="{% url 'produto:delete' pk=produto.id %}"><button type="button" class="btn btn-outline-danger">Deletar</button></a>
                <a href="{% url 'produto:detalhe' pk=produto.id %}"><button type="button" class="btn btn-outline-secondary">Comprar</button></a>
                
              
              </div>
            </div>  
          {% endif %}              
          {% endfor %}
    
        </div>
        <div style="margin-top: 20px;">
          <a href="{% url 'produto:carrinho'%}"><button onclick="PushSession()" type="button" class="btn btn-outline-secondary"> Meu carrinho</button></a>
        </div>
        <div style="margin-top: 30px;">

          <form>
            <div class="form-group">
              
              {{ filter.form }}
    
            </div>
            <button type="submit" class="btn btn-primary mb-2">O que desejas?</button>
          </form>
        </div>

            <script>
              let carrinho = []

              function RemoveCarrinho(id) {
                pos = carrinho.indexOf(id)

                while(pos >= 0){
                    carrinho.splice(pos, 1);
                    pos = carrinho.indexOf(id);
                }

                elemento = document.getElementById(id)
                elemento.innerHTML = `
                <a id="${id}"><button onclick="AddCarrinho('${id}')" type="button" class="btn btn-outline-secondary">Adicionar a carrinho</button></a>
                `

                console.log(carrinho)
              }

              function AddCarrinho(id) {
                if (carrinho.indexOf(id) ===  -1) {
                  
                  carrinho.push(id)
                  
                  elemento = document.getElementById(id)
                  elemento.innerHTML = `
                  <a id="${id}"><button onclick="RemoveCarrinho('${id}')" type="button" class="btn btn-outline-secondary">Remover do Carrinho</button></a>
                  `
                  console.log(carrinho)
                }
              }

              function PushSession() {
                document.cookie = `produtos= ${carrinho}`
              }
            </script>  

    {% else %}
        Não há produtos disponíveis
    {% endif %}
    
{% endblock %}  